replicaCount: 1
image:
  repository: realsahilthakur/backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
env:
  DB_HOST: postgres
  DB_NAME: anime_db
  DB_USER: user
  DB_PASSWORD: password
